# Generated by Django 5.2.5 on 2025-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('attending_provider', models.CharField(blank=True, max_length=120)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['mrn'], name='patients_pa_mrn_d0102f_idx'), models.Index(fields=['name'], name='patients_pa_name_8d04ea_idx'), models.Index(fields=['location'], name='patients_pa_locatio_fb566c_idx')],
            },
        ),
    ]
