# Generated by Django 5.2.5 on 2025-08-20 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signouts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signouts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Signout entry',
                'verbose_name_plural': 'Signout entries',
                'ordering': ['entry_date', 'created_at'],
                'indexes': [models.Index(fields=['entry_date'], name='patients_si_entry_d_837f81_idx')],
                'unique_together': {('patient', 'entry_date', 'created_at')},
            },
        ),
    ]
