# Generated by Django 5.2.5 on 2025-08-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Watchlist entry',
                'verbose_name_plural': 'Watchlist entries',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='attending',
            field=models.ForeignKey(blank=True, help_text='Official attending physician for census', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['attending'], name='patients_pa_attendi_c96814_idx'),
        ),
        migrations.AddField(
            model_name='watch',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(help_text='The user who is watching this patient', on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['user'], name='patients_wa_user_id_bea4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['patient'], name='patients_wa_patient_09955b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watch',
            unique_together={('user', 'patient')},
        ),
    ]
