# Generated by Django 5.2.5 on 2025-08-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_watch_patient_attending_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_completed', '-created_at'], 'verbose_name': 'To-do', 'verbose_name_plural': 'To-dos'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='attending_provider',
        ),
    ]
