# Generated by Django 5.2.5 on 2025-08-20 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_set_null_attendings_to_tba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watch',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-start_date', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='overnightevent',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-admission_date', '-admission_time', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='signout',
            options={'ordering': ('-entry_date', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('is_completed', '-created_at'), 'verbose_name': 'To‑Do', 'verbose_name_plural': 'To‑Dos'},
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_locatio_fb566c_idx',
        ),
        migrations.RemoveIndex(
            model_name='signout',
            name='patients_si_entry_d_837f81_idx',
        ),
        migrations.RemoveIndex(
            model_name='todo',
            name='patients_to_is_comp_f946a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='todo',
            name='patients_to_expires_1eda27_idx',
        ),
        migrations.AlterUniqueTogether(
            name='signout',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(max_length=32, unique=True, verbose_name='MRN'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='signout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_signouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['provider'], name='patients_as_provide_97f435_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date'], name='patients_as_start_d_3058ca_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['admission_date', 'admission_time'], name='patients_pa_admissi_92123e_idx'),
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
