# Generated by Django 5.2.5 on 2025-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_archived_at_patient_discharged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_information',
            field=models.TextField(blank=True, help_text='Admission-day narrative or key summary for this patient.', verbose_name='Patient Information'),
        ),
    ]
