# Generated by Django 5.2.5 on 2025-08-22 03:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_todo_options_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-visible_at', '-created_at')},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='patients_no_recipie_b56c5c_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='visible_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'visible_at'], name='patients_no_recipie_5bfbf1_idx'),
        ),
    ]
