# Generated by Django 5.2.5 on 2025-08-22 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_notification_notify_unread_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('generic', 'Generic'), ('assignment', 'Patient Assignment')], db_index=True, default='generic', max_length=32),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['kind', 'patient', 'visible_at'], name='patients_no_kind_7c28e5_idx'),
        ),
    ]
