# Generated by Django 5.2.5 on 2025-08-22 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_notification_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ATTENDING_CHANGED', 'Attending changed')], max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('new_attending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_new_attending', to=settings.AUTH_USER_MODEL)),
                ('old_attending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_old_attending', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'created_at'], name='patients_au_event_6dd639_idx'), models.Index(fields=['patient', 'created_at'], name='patients_au_patient_a72b89_idx')],
            },
        ),
    ]
