# Generated by Django 5.2.5 on 2025-08-22 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patientwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
